/**
 * (c) 2016 Unicorn.JS
 * Wrapper made by Alexandro Sanchez Bach.
 */

// Unicorn MIPS extensions
uc.extend({
    // Registers
    UC_MIPS_REG_INVALID:             0,
    UC_MIPS_REG_PC:                  1,
    UC_MIPS_REG_0:                   2,
    UC_MIPS_REG_1:                   3,
    UC_MIPS_REG_2:                   4,
    UC_MIPS_REG_3:                   5,
    UC_MIPS_REG_4:                   6,
    UC_MIPS_REG_5:                   7,
    UC_MIPS_REG_6:                   8,
    UC_MIPS_REG_7:                   9,
    UC_MIPS_REG_8:                  10,
    UC_MIPS_REG_9:                  11,
    UC_MIPS_REG_10:                 12,
    UC_MIPS_REG_11:                 13,
    UC_MIPS_REG_12:                 14,
    UC_MIPS_REG_13:                 15,
    UC_MIPS_REG_14:                 16,
    UC_MIPS_REG_15:                 17,
    UC_MIPS_REG_16:                 18,
    UC_MIPS_REG_17:                 19,
    UC_MIPS_REG_18:                 20,
    UC_MIPS_REG_19:                 21,
    UC_MIPS_REG_20:                 22,
    UC_MIPS_REG_21:                 23,
    UC_MIPS_REG_22:                 24,
    UC_MIPS_REG_23:                 25,
    UC_MIPS_REG_24:                 26,
    UC_MIPS_REG_25:                 27,
    UC_MIPS_REG_26:                 28,
    UC_MIPS_REG_27:                 29,
    UC_MIPS_REG_28:                 30,
    UC_MIPS_REG_29:                 31,
    UC_MIPS_REG_30:                 32,
    UC_MIPS_REG_31:                 33,

    // DSP registers
    UC_MIPS_REG_DSPCCOND:           34,
    UC_MIPS_REG_DSPCARRY:           35,
    UC_MIPS_REG_DSPEFI:             36,
    UC_MIPS_REG_DSPOUTFLAG:         37,
    UC_MIPS_REG_DSPOUTFLAG16_19:    38,
    UC_MIPS_REG_DSPOUTFLAG20:       39,
    UC_MIPS_REG_DSPOUTFLAG21:       40,
    UC_MIPS_REG_DSPOUTFLAG22:       41,
    UC_MIPS_REG_DSPOUTFLAG23:       42,
    UC_MIPS_REG_DSPPOS:             43,
    UC_MIPS_REG_DSPSCOUNT:          44,

    // ACC registers
    UC_MIPS_REG_AC0:                45,
    UC_MIPS_REG_AC1:                46,
    UC_MIPS_REG_AC2:                47,
    UC_MIPS_REG_AC3:                48,

    // COP registers
    UC_MIPS_REG_CC0:                49,
    UC_MIPS_REG_CC2:                50,
    UC_MIPS_REG_CC3:                51,
    UC_MIPS_REG_CC4:                52,
    UC_MIPS_REG_CC5:                53,
    UC_MIPS_REG_CC6:                54,
    UC_MIPS_REG_CC7:                55,

    // FPU registers
    UC_MIPS_REG_F0:                 56,
    UC_MIPS_REG_F1:                 57,
    UC_MIPS_REG_F2:                 58,
    UC_MIPS_REG_F3:                 59,
    UC_MIPS_REG_F4:                 60,
    UC_MIPS_REG_F5:                 61,
    UC_MIPS_REG_F6:                 62,
    UC_MIPS_REG_F7:                 63,
    UC_MIPS_REG_F8:                 64,
    UC_MIPS_REG_F9:                 65,
    UC_MIPS_REG_F10:                66,
    UC_MIPS_REG_F11:                67,
    UC_MIPS_REG_F12:                68,
    UC_MIPS_REG_F13:                69,
    UC_MIPS_REG_F14:                70,
    UC_MIPS_REG_F15:                71,
    UC_MIPS_REG_F16:                72,
    UC_MIPS_REG_F17:                73,
    UC_MIPS_REG_F18:                74,
    UC_MIPS_REG_F19:                75,
    UC_MIPS_REG_F20:                76,
    UC_MIPS_REG_F21:                77,
    UC_MIPS_REG_F22:                78,
    UC_MIPS_REG_F23:                79,
    UC_MIPS_REG_F24:                80,
    UC_MIPS_REG_F25:                81,
    UC_MIPS_REG_F26:                82,
    UC_MIPS_REG_F27:                83,
    UC_MIPS_REG_F28:                84,
    UC_MIPS_REG_F29:                85,
    UC_MIPS_REG_F30:                86,
    UC_MIPS_REG_F31:                87,
    UC_MIPS_REG_FCC0:               88,
    UC_MIPS_REG_FCC1:               89,
    UC_MIPS_REG_FCC2:               90,
    UC_MIPS_REG_FCC3:               91,
    UC_MIPS_REG_FCC4:               92,
    UC_MIPS_REG_FCC5:               93,
    UC_MIPS_REG_FCC6:               94,
    UC_MIPS_REG_FCC7:               95,

    // AFPR128 registers
    UC_MIPS_REG_W0:                 96,
    UC_MIPS_REG_W1:                 97,
    UC_MIPS_REG_W2:                 98,
    UC_MIPS_REG_W3:                 99,
    UC_MIPS_REG_W4:                100,
    UC_MIPS_REG_W5:                101,
    UC_MIPS_REG_W6:                102,
    UC_MIPS_REG_W7:                103,
    UC_MIPS_REG_W8:                104,
    UC_MIPS_REG_W9:                105,
    UC_MIPS_REG_W10:               106,
    UC_MIPS_REG_W11:               107,
    UC_MIPS_REG_W12:               108,
    UC_MIPS_REG_W13:               109,
    UC_MIPS_REG_W14:               110,
    UC_MIPS_REG_W15:               111,
    UC_MIPS_REG_W16:               112,
    UC_MIPS_REG_W17:               113,
    UC_MIPS_REG_W18:               114,
    UC_MIPS_REG_W19:               115,
    UC_MIPS_REG_W20:               116,
    UC_MIPS_REG_W21:               117,
    UC_MIPS_REG_W22:               118,
    UC_MIPS_REG_W23:               119,
    UC_MIPS_REG_W24:               120,
    UC_MIPS_REG_W25:               121,
    UC_MIPS_REG_W26:               122,
    UC_MIPS_REG_W27:               123,
    UC_MIPS_REG_W28:               124,
    UC_MIPS_REG_W29:               125,
    UC_MIPS_REG_W30:               126,
    UC_MIPS_REG_W31:               127,
    UC_MIPS_REG_HI:                128,
    UC_MIPS_REG_LO:                129,
    UC_MIPS_REG_P0:                130,
    UC_MIPS_REG_P1:                131,
    UC_MIPS_REG_P2:                132,
    UC_MIPS_REG_MPL0:              133,
    UC_MIPS_REG_MPL1:              134,
    UC_MIPS_REG_MPL2:              135,

    // Alias-registers
    UC_MIPS_REG_ZERO:  UC_MIPS_REG_0,
    UC_MIPS_REG_AT:    UC_MIPS_REG_1,
    UC_MIPS_REG_V0:    UC_MIPS_REG_2,
    UC_MIPS_REG_V1:    UC_MIPS_REG_3,
    UC_MIPS_REG_A0:    UC_MIPS_REG_4,
    UC_MIPS_REG_A1:    UC_MIPS_REG_5,
    UC_MIPS_REG_A2:    UC_MIPS_REG_6,
    UC_MIPS_REG_A3:    UC_MIPS_REG_7,
    UC_MIPS_REG_T0:    UC_MIPS_REG_8,
    UC_MIPS_REG_T1:    UC_MIPS_REG_9,
    UC_MIPS_REG_T2:    UC_MIPS_REG_10,
    UC_MIPS_REG_T3:    UC_MIPS_REG_11,
    UC_MIPS_REG_T4:    UC_MIPS_REG_12,
    UC_MIPS_REG_T5:    UC_MIPS_REG_13,
    UC_MIPS_REG_T6:    UC_MIPS_REG_14,
    UC_MIPS_REG_T7:    UC_MIPS_REG_15,
    UC_MIPS_REG_S0:    UC_MIPS_REG_16,
    UC_MIPS_REG_S1:    UC_MIPS_REG_17,
    UC_MIPS_REG_S2:    UC_MIPS_REG_18,
    UC_MIPS_REG_S3:    UC_MIPS_REG_19,
    UC_MIPS_REG_S4:    UC_MIPS_REG_20,
    UC_MIPS_REG_S5:    UC_MIPS_REG_21,
    UC_MIPS_REG_S6:    UC_MIPS_REG_22,
    UC_MIPS_REG_S7:    UC_MIPS_REG_23,
    UC_MIPS_REG_T8:    UC_MIPS_REG_24,
    UC_MIPS_REG_T9:    UC_MIPS_REG_25,
    UC_MIPS_REG_K0:    UC_MIPS_REG_26,
    UC_MIPS_REG_K1:    UC_MIPS_REG_27,
    UC_MIPS_REG_GP:    UC_MIPS_REG_28,
    UC_MIPS_REG_SP:    UC_MIPS_REG_29,
    UC_MIPS_REG_FP:    UC_MIPS_REG_30,
    UC_MIPS_REG_S8:    UC_MIPS_REG_30,
    UC_MIPS_REG_RA:    UC_MIPS_REG_31,
    UC_MIPS_REG_HI0:   UC_MIPS_REG_AC0,
    UC_MIPS_REG_HI1:   UC_MIPS_REG_AC1,
    UC_MIPS_REG_HI2:   UC_MIPS_REG_AC2,
    UC_MIPS_REG_HI3:   UC_MIPS_REG_AC3,
    UC_MIPS_REG_LO0:   UC_MIPS_REG_HI0,
    UC_MIPS_REG_LO1:   UC_MIPS_REG_HI1,
    UC_MIPS_REG_LO2:   UC_MIPS_REG_HI2,
    UC_MIPS_REG_LO3:   UC_MIPS_REG_HI3,
});
